table Territory


    column 'TerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: TerritoryID

        annotation SummarizationSetBy = Automatic

        
        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        annotation SummarizationSetBy = Automatic

        
        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        annotation SummarizationSetBy = Automatic

        
        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
        
    column 'datecreated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
        variation Variation
            isDefault
            relationship: 791d5dac-fabc-47df-bf82-d8cb33ab5565
            defaultHierarchy: LocalDateTable_e288f074-73db-4f06-82c2-71cd3834a83f.'Date Hierarchy'
        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
        
    column 'LastUpdated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
        variation Variation
            isDefault
            relationship: dc9ad1ff-cd3c-4dcf-9a0a-0a8cfe639fed
            defaultHierarchy: LocalDateTable_e288f074-73db-4f06-82c2-71cd3834a83f.'Date Hierarchy'
        



    partition 'Territory' = m
        mode: import
        source = 
            // ERROR: Error communicating with LLM service for table Territory: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/m-query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1049e81d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
let
				Source = Table.FromRows({})
				in
				Source
        



    annotation PBI_ResultType = Table