table Territory


    column 'TerritoryID'
        dataType: int64
        summarizeBy: none
        sourceColumn: TerritoryID

        annotation SummarizationSetBy = Automatic

        
        
    column 'Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Name

        annotation SummarizationSetBy = Automatic

        
        
    column 'IsActive'
        dataType: string
        summarizeBy: none
        sourceColumn: IsActive

        annotation SummarizationSetBy = Automatic

        
        
    column 'CreatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: CreatedBy

        annotation SummarizationSetBy = Automatic

        
        
    column 'datecreated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: datecreated

        annotation SummarizationSetBy = Automatic

        
        variation Variation
            isDefault
            relationship: 3b63f228-7d48-4cbf-8205-897b6bd80c9a
            defaultHierarchy: &#x27;LocalDateTable_eb89bb98-05b4-4cae-8360-6e958c15265d&#x27;.&#x27;Date Hierarchy&#x27;
        
    column 'UpdatedBy'
        dataType: string
        summarizeBy: none
        sourceColumn: UpdatedBy

        annotation SummarizationSetBy = Automatic

        
        
    column 'LastUpdated'
        dataType: dateTime
        summarizeBy: none
        sourceColumn: LastUpdated

        annotation SummarizationSetBy = Automatic

        
        variation Variation
            isDefault
            relationship: 478f9726-fe72-4d13-8276-e3e25e59f1f5
            defaultHierarchy: &#x27;LocalDateTable_eb89bb98-05b4-4cae-8360-6e958c15265d&#x27;.&#x27;Date Hierarchy&#x27;
        



    partition 'Territory' = m
        mode: import
        source = 
            // ERROR: Error communicating with LLM service for table Territory: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/m-query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11009d640>: Failed to establish a new connection: [Errno 61] Connection refused'))
let
				Source = Table.FromRows({})
				in
				Source
        



    annotation PBI_ResultType = Table